### ISSUE TITLE
Can't get wibar to setup properly

### ISSUE THREAD

**Issue by 401-No-Username** [lVoidi/dots#9]
![picture](https://user-images.githubusercontent.com/94318495/141696740-39378b28-89b9-4a0d-8f58-f495d8b787da.png)

I double-checked and have all the files downloaded in ~/.config/awesome/
Downloaded awesome-git from the AUR

**Comment by MrJakeSir** [comment]
thats because you have a larger screen, i don't know how i can help, i have a 1920x1080 screen so i made the configuration based on a 1080 screen

**Comment by lVoidi** [comment]
Fixed
I think this problem no longer happens
